name: Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Checkout libxlsxwriter
        uses: actions/checkout@v2
        with: 
          repository: jmcnamara/libxlsxwriter
          path: libxlsxwriter
          
      - name: Build libxlsxwriter
        working-directory: ./libxlsxwriter
        run: |
          make
          sudo make install

      - name: Build Debug mode
        run: swift build 

      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          module-name: "xlsxwriter"
          output: "./documentation"
          format: "html"
          base-url: "https://damuellen.github.io/xlsxwriter.swift/"
          
      - run: sudo chown -R $USER:$USER ./documentation
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: "./documentation"
