name: Windows

on:
  push:
    branches: [windows]
    
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5-release
          tag: 5.5-RELEASE

      - uses: actions/checkout@v2
        with:
          ref: windows

      - run: swift build -Xswifc -LC:/vcpkg/installed/x64-windows/lib
